FROM mcr.microsoft.com/mssql-tools

COPY ./src/main/resources/sql-init /sql-init
COPY ./run-init-scripts.sh /run-init-scripts.sh

RUN chmod +x /run-init-scripts.sh

ENTRYPOINT ["/bin/sh", "/run-init-scripts.sh"]
